backend:
  replicaCount: 1
  image:
    repository: ghcr.io/timfbr03/cloud-computing-dski/backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3001
  ingress:
    enabled: false

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/timfbr03/cloud-computing-dski/frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: myfrontend.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

database:
  replicaCount: 1
  image:
    repository: ghcr.io/timfbr03/cloud-computing-dski/database
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  ingress:
    enabled: false
