apiVersion: v2
name: todo-app
description: Helm chart for todo frontend, backend, and database
version: 0.1.0
type: application
dependencies:
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts