{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.servicePort }}
      targetPort: {{ $svc.containerPort }}
      protocol: TCP
---
{{- end }}