# storage.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hadoop-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
# NameNode PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hadoop-storage
  hostPath:
    path: /data/hadoop/namenode

---
# DataNode PV Template
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-pv-1
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hadoop-storage
  hostPath:
    path: /data/hadoop/datanode-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-pv-2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hadoop-storage
  hostPath:
    path: /data/hadoop/datanode-2
