apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-calculator-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: myapi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapi
                port:
                  number: 4000
