# datanode.yaml - Super vereinfacht ohne Custom Config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-datanode
  namespace: hadoop-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hadoop-datanode
  template:
    metadata:
      labels:
        app: hadoop-datanode
    spec:
      containers:
        - name: datanode
          image: apache/hadoop:3
          command: ["/bin/bash", "-c"]
          args:
            - |
              # Wait for namenode
              echo "Waiting for NameNode..."
              until nc -z hadoop-namenode 9000; do
                echo "NameNode not ready, waiting..."
                sleep 5
              done
              
              echo "Starting DataNode..."
              /opt/hadoop/bin/hdfs datanode
          ports:
            - containerPort: 9864
              name: http
            - containerPort: 9866
              name: data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /
              port: 9864
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 9864
            initialDelaySeconds: 120
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode
  namespace: hadoop-cluster
spec:
  selector:
    app: hadoop-datanode
  ports:
    - name: http
      port: 9864
      targetPort: 9864
    - name: data
      port: 9866
      targetPort: 9866