# datanode.yaml - Fixed für lokalen Speicher
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-datanode
  namespace: hadoop-cluster
spec:
  serviceName: hadoop-datanode
  replicas: 2  # Reduziert von 3 auf 2
  selector:
    matchLabels:
      app: hadoop-datanode
  template:
    metadata:
      labels:
        app: hadoop-datanode
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ['sh', '-c', 'mkdir -p /hadoop/dfs/data && chown -R 1000:1000 /hadoop/dfs/data']
          volumeMounts:
            - name: datanode-data
              mountPath: /hadoop/dfs/data
          securityContext:
            runAsUser: 0
      containers:
        - name: datanode
          image: apache/hadoop:3
          command: ["/bin/bash"]
          args:
            - -c
            - |
              # Wait for namenode to be ready
              echo "Waiting for NameNode..."
              until nc -z hadoop-namenode 9000; do
                echo "NameNode not ready, waiting..."
                sleep 10
              done
              echo "NameNode is ready, starting DataNode"
              
              # Start datanode
              /opt/hadoop/bin/hdfs datanode
          env:
            - name: HDFS_CONF_dfs_datanode_data_dir
              value: "/hadoop/dfs/data"
            - name: JAVA_HOME
              value: "/opt/java/openjdk"
          ports:
            - containerPort: 9864
              name: http
            - containerPort: 9866
              name: data
            - containerPort: 9867
              name: ipc
          volumeMounts:
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop
            - name: datanode-data
              mountPath: /hadoop/dfs/data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /
              port: 9864
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          livenessProbe:
            httpGet:
              path: /
              port: 9864
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 10
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
        - name: datanode-data
          emptyDir:
            sizeLimit: "3Gi"  # Begrenzt auf 3GB pro DataNode

---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode
  namespace: hadoop-cluster
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hadoop-datanode
  ports:
    - name: http
      port: 9864
      targetPort: 9864
    - name: data
      port: 9866
      targetPort: 9866
    - name: ipc
      port: 9867
      targetPort: 9867