# namenode.yaml - Super vereinfacht ohne Custom Config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-namenode
  namespace: hadoop-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-namenode
  template:
    metadata:
      labels:
        app: hadoop-namenode
    spec:
      containers:
        - name: namenode
          image: apache/hadoop:3
          command: ["/bin/bash", "-c"]
          args:
            - |
              # Format if needed (using default config)
              if [ ! -d /tmp/hadoop-*/dfs/name/current ]; then
                echo "Formatting NameNode with default config..."
                /opt/hadoop/bin/hdfs namenode -format -force -clusterId test-cluster
              fi
              
              echo "Starting NameNode..."
              /opt/hadoop/bin/hdfs namenode
          ports:
            - containerPort: 9000
              name: rpc
            - containerPort: 9870
              name: http
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /
              port: 9870
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 9870
            initialDelaySeconds: 120
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
  namespace: hadoop-cluster
spec:
  selector:
    app: hadoop-namenode
  ports:
    - name: rpc
      port: 9000
      targetPort: 9000
    - name: http
      port: 9870
      targetPort: 9870

---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode-web
  namespace: hadoop-cluster
spec:
  type: NodePort
  selector:
    app: hadoop-namenode
  ports:
    - name: web
      port: 9870
      targetPort: 9870
      nodePort: 30091