---
# Backend ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todo-app
data:
  DATABASE_URL: "postgresql://todouser:todopass@todo-database-service:5432/todoapp"
  PORT: "3001"

---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-app
  labels:
    app: todo-backend
spec:
  replicas: 1  # Reduced for k3s
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: todo-backend:latest
        imagePullPolicy: Never  # For local k3s development
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_URL
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"   # Reduced for k3s
            cpu: "50m"
          limits:
            memory: "256Mi"  # Reduced for k3s
            cpu: "200m"

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  namespace: todo-app
  labels:
    app: todo-backend
spec:
  selector:
    app: todo-backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP