apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-traefik-config
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
  traefik.toml: |
    [entryPoints]
      [entryPoints.web]
        address = ":80"
    
    [providers.kubernetesCRD]
      namespaces = ["{{ .Release.Namespace }}"]
    
    [providers.kubernetesIngress]
      namespaces = ["{{ .Release.Namespace }}"]
    
    [api]
      insecure = true
      dashboard = true