replicaCount: 1

image:
  repository: ghcr.io/timfbr03/cloud-computing-dski
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: myapi.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
