replicaCount: 1

image:
  repository: ghcr.io/timfbr03/cloud-computing-dski
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []