apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}-secret
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.database.env.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.database.env.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_DB: {{ .Values.database.env.POSTGRES_DB | b64enc }}