{{- range $serviceName, $service := .Values }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
spec:
  type: {{ $service.service.type }}
  selector:
    app: {{ $serviceName }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: {{ $service.service.port }}
{{- end }}
